//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int AnswerId { get; set; }
        public Nullable<int> QAid { get; set; }
        public Nullable<int> AnsweredBy { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> AnsweredOn { get; set; }
        public Nullable<int> LikesCount { get; set; }
        public Nullable<int> DislikesCount { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
    
        public virtual PortalRegistration PortalRegistration { get; set; }
        public virtual QuestionAnswer QuestionAnswer { get; set; }
    }
}
