//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeProjectGuide
    {
        public int CollegeGuideId { get; set; }
        public Nullable<int> RegID { get; set; }
        public string Name { get; set; }
        public string CollegeName { get; set; }
        public string University { get; set; }
        public string Contact { get; set; }
        public string CollegeIdCard { get; set; }
        public string IdProof { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
    
        public virtual PortalRegistration PortalRegistration { get; set; }
    }
}
