//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternshipApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternshipApplication()
        {
            this.Team = new HashSet<Team>();
        }
    
        public int ApplicationID { get; set; }
        public Nullable<int> RegID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Location { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<int> Semester { get; set; }
        public string CollegeIDCard { get; set; }
        public string IdProof { get; set; }
        public string NOCLetter { get; set; }
        public string CollegeName { get; set; }
        public string University { get; set; }
        public Nullable<System.DateTime> ProjectSubmissionDate { get; set; }
        public string CollegeProjectGuide { get; set; }
        public string CollegeProjectGuideEmail { get; set; }
        public Nullable<int> CollegeProjectGuideContact { get; set; }
        public string Reference { get; set; }
        public Nullable<int> ApplicationStatus { get; set; }
        public string ApprovalLetter { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
    
        public virtual PortalRegistration PortalRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Team { get; set; }
    }
}
